# PHP
# Test and package your PHP project.
# Add steps that run tests, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/php

trigger:
  batch: 'true'
  branches:
    include:
      - master
  tags:
    include:
      - '*'
pr:
  autoCancel: 'true'
  branches:
    include:
      - '*'

variables:
  - group: Monica
  - name: COMPOSER_HOME
    value: $(Pipeline.Workspace)/.composer
  - name: YARN_CACHE_FOLDER
    value: $(Pipeline.Workspace)/.yarn

stages:
  - stage: build
    displayName: 'Build'
    condition: not(startsWith(variables['System.PullRequest.SourceBranch'], 'l10n_master'))
    jobs:
      - template: .azure/job-build.yml
      - template: .azure/job-tests.yml
      - template: .azure/job-analyzers.yml
      - template: .azure/job-test-browser.yml
      - template: .azure/job-reporting.yml
      - template: .azure/job-test-migrations.yml

  - ${{ if and(in(variables['Build.Reason'], 'IndividualCI', 'BatchedCI'), startsWith(variables['Build.SourceBranch'], 'refs/tags/')) }}:
      - stage: deploy
        displayName: Deploy
        dependsOn: build

        jobs:
          - deployment: deploy_dist
            pool:
              vmImage: 'ubuntu-latest'
            environment: monica
            strategy:
              runOnce:
                deploy:
                  steps:
                    - download: none
                    - checkout: self
                    - template: .azure/step-composer-install.yml
                      parameters:
                        no_dev: true
                    - template: .azure/step-deploy-dist.yml
