# PHP
# Test and package your PHP project.
# Add steps that run tests, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/php

trigger:
  batch: true
  branches:
    include:
      - master
  tags:
    include:
      - '*'
pr:
  autoCancel: true
  branches:
    include:
      - '*'

variables:
  - group: Monica
  - name: phpVersion
    value: 7.4
  - name: COMPOSER_HOME
    value: $(Pipeline.Workspace)/.composer
  - name: YARN_CACHE_FOLDER
    value: $(Pipeline.Workspace)/.yarn

stages:
  - stage: build
    displayName: Build
    condition: not(startsWith(variables['System.PullRequest.SourceBranch'], 'l10n_master'))
    jobs:
      - template: .azure/job-build.yml
      - template: .azure/job-tests.yml
      - template: .azure/job-analyzers.yml
      - template: .azure/job-test-browser.yml
      - template: .azure/job-reporting.yml
      - template: .azure/job-test-migrations.yml
