commit_message: '[skip ci]'
files:
  - source: /resources/lang/en/*.php
    translation: /resources/lang/%two_letters_code%/%original_file_name%
    languages_mapping:
      two_letters_code:
        'en-GB' : 'en-GB'
        'pt-BR' : 'pt-BR'
  - source: /resources/lang/vendor/confirmation/en/*.php
    translation: /resources/lang/vendor/confirmation/%two_letters_code%/%original_file_name%
    languages_mapping:
      two_letters_code:
        'en-GB' : 'en-GB'
        'pt-BR' : 'pt-BR'
  - source: /resources/lang/vendor/webauthn/en/*.php
    translation: /resources/lang/vendor/webauthn/%two_letters_code%/%original_file_name%
    languages_mapping:
      two_letters_code:
        'en-GB' : 'en-GB'
        'pt-BR' : 'pt-BR'
