commit_message: '[skip ci]'
project_id_env: CROWDIN_PROJECT_ID
api_token_env: CROWDIN_PERSONAL_TOKEN
files:
  - source: /resources/lang/en/*.php
    translation: /resources/lang/%two_letters_code%/%original_file_name%
    languages_mapping:
      two_letters_code:
        en-GB: en-GB
        pt-BR: pt-BR
        zh-CN: zh
        zh-TW: zh-TW
  - source: /resources/lang/vendor/confirmation/en/*.php
    translation: /resources/lang/vendor/confirmation/%two_letters_code%/%original_file_name%
    languages_mapping:
      two_letters_code:
        en-GB: en-GB
        pt-BR: pt-BR
        zh-CN: zh
        zh-TW: zh-TW
  - source: /resources/lang/vendor/webauthn/en/*.php
    translation: /resources/lang/vendor/webauthn/%two_letters_code%/%original_file_name%
    languages_mapping:
      two_letters_code:
        en-GB: en-GB
        pt-BR: pt-BR
        zh-CN: zh
        zh-TW: zh-TW
  - source: /resources/lang/en.json
    translation: /resources/lang/%two_letters_code%.json
    languages_mapping:
      two_letters_code:
        en-GB: en-GB
        pt-BR: pt-BR
        zh-CN: zh
        zh-TW: zh-TW
