jobs:
- job: build
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - template: prepare-environment-step.yml
  - template: composer-install-step.yml

  - bash: |
      yarn global add greenkeeper-lockfile@1
    displayName: 'Install greenkeeper'

#      SYSTEM_PULLREQUEST_PULLREQUESTID=$(test "$BUILD_SOURCEBRANCHNAME" != "master" -a "greenkeeper[bot]" = "`git log --format="%an" -n 1`" || echo '') GK_LOCK_YARN_OPTS="--ignore-engines" $(yarn global bin)/greenkeeper-lockfile-update
  - bash: |
      source scripts/ci/fixsecrets.sh
      TRAVIS=true TRAVIS_REPO_SLUG=$BUILD_REPOSITORY_NAME TRAVIS_BRANCH=$SYSTEM_PULLREQUEST_SOURCEBRANCH TRAVIS_PULL_REQUEST=false TRAVIS_JOB_NUMBER=1 GK_LOCK_YARN_OPTS="--ignore-engines" $(yarn global bin)/greenkeeper-lockfile-update
    displayName: 'Update yarn lockfile'
    env:
      GH_TOKEN: $(GH_TOKEN)
  - bash: yarn inst
    displayName: 'yarn install'
#      SYSTEM_PULLREQUEST_PULLREQUESTID=$(test "$BUILD_SOURCEBRANCHNAME" != "master" -a "greenkeeperio-bot" = "`git log --format="%an" -n 1`" || echo '') $(yarn global bin)/greenkeeper-lockfile-upload
  - bash: |
      source scripts/ci/fixsecrets.sh
      TRAVIS=true TRAVIS_REPO_SLUG=$BUILD_REPOSITORY_NAME TRAVIS_BRANCH=$SYSTEM_PULLREQUEST_SOURCEBRANCH TRAVIS_PULL_REQUEST=false TRAVIS_JOB_NUMBER=1 $(yarn global bin)/greenkeeper-lockfile-upload
      cat gk-lockfile-git-push.err || true
      rm -f gk-lockfile-git-push.err || true
    displayName: 'Upload yarn lockfile'
    env:
      GH_TOKEN: $(GH_TOKEN)

  # Update js and css assets eventually
  - bash: yarn lint
    displayName: 'Check js and vue lint'
  - bash: |
      source scripts/ci/fixsecrets.sh
      scripts/ci/update-assets.sh
    displayName: 'Update assets'
    env:
      ASSETS_USERNAME: $(ASSETS_USERNAME)
      ASSETS_EMAIL: $(ASSETS_EMAIL)
      ASSETS_GITHUB_TOKEN: $(ASSETS_GITHUB_TOKEN)
