jobs:
- job: build
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - template: prepare-environment-step.yml
  - template: composer-install-step.yml

  - bash: |
      yarn global add greenkeeper-lockfile@2
    displayName: 'Install greenkeeper'

  - bash: |
      source scripts/ci/fixsecrets.sh
      $(yarn global bin)/greenkeeper-lockfile-update
    displayName: 'Update yarn lockfile'
    env:
      TRAVIS: true
      TRAVIS_REPO_SLUG: $(Build.Repository.Name)
      TRAVIS_BRANCH: $(System.PullRequest.SourceBranch)
      TRAVIS_PULL_REQUEST: false
      TRAVIS_JOB_NUMBER: .1
      GK_LOCK_YARN_OPTS: --ignore-engines
      GH_TOKEN: $(GH_TOKEN)
      GK_LOCK_DEBUG: true

  - bash: yarn inst
    displayName: 'yarn install'

  - bash: |
      source scripts/ci/fixsecrets.sh
      $(yarn global bin)/greenkeeper-lockfile-upload
      cat gk-lockfile-git-push.err || true
      rm -f gk-lockfile-git-push.err || true
    displayName: 'Upload yarn lockfile'
    env:
      TRAVIS: true
      TRAVIS_REPO_SLUG: $(Build.Repository.Name)
      TRAVIS_BRANCH: $(System.PullRequest.SourceBranch)
      TRAVIS_PULL_REQUEST: false
      TRAVIS_JOB_NUMBER: .1
      GH_TOKEN: $(GH_TOKEN)
      GK_LOCK_DEBUG: true

  # Update js and css assets eventually
  - bash: yarn lint
    displayName: 'Check js and vue lint'
  - bash: |
      source scripts/ci/fixsecrets.sh
      scripts/ci/update-assets.sh
    displayName: 'Update assets'
    env:
      ASSETS_USERNAME: $(ASSETS_USERNAME)
      ASSETS_EMAIL: $(ASSETS_EMAIL)
      ASSETS_GITHUB_TOKEN: $(ASSETS_GITHUB_TOKEN)
