parameters:
  no_dev: 'false'
steps:
- task: CacheBeta@0
  inputs:
    key: composer-v2 | composer.lock
    path: $(COMPOSER_HOME)/cache
  displayName: Cache composer packages
- bash: |
    sudo composer self-update
    export EXTRA_PARAM=$(test "${{ parameters.no_dev }}" == "true" && echo "--no-dev")
    composer install --no-interaction --no-suggest --no-progress --ignore-platform-reqs ${EXTRA_PARAM:-}
  displayName: 'composer install'
