jobs:
- job: build
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - template: step-prepare-environment.yml
  - template: step-composer-install.yml

  - template: step-cache-yarn.yml

  - script: yarn inst
    displayName: 'yarn install'

  # Update js and css assets eventually
  - script: yarn lint:all
    displayName: 'Check js and vue lint'
  - bash: |
      source scripts/ci/fixsecrets.sh
      scripts/ci/update-assets.sh
    displayName: 'Update assets'
    env:
      ASSETS_USERNAME: $(ASSETS_USERNAME)
      ASSETS_EMAIL: $(ASSETS_EMAIL)
      ASSETS_GITHUB_TOKEN: $(ASSETS_GITHUB_TOKEN)
