jobs:
- job: psalm
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - template: step-prepare-environment.yml
  - template: step-composer-install.yml

  - script: vendor/bin/psalm --shepherd
    displayName: Run psalm

- job: phpstan
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - template: step-prepare-environment.yml
  - template: step-composer-install.yml

  - script: vendor/bin/phpstan analyse
    displayName: Run phpstan
