jobs:
- job: test_migrations
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - template: step-prepare-environment.yml
  - template: step-composer-install.yml
  - template: step-prepare-db.yml
    parameters:
      import: false
