jobs:
- job: tests_browser
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - template: step-prepare-environment.yml
  - template: step-composer-install.yml
  - template: step-prepare-db.yml
  - template: step-seed-test-db.yml

  - template: step-test-browser.yml

  - bash: |
      vendor/bin/phpcov merge --clover=results/coverage0.xml results/coverage/
      rm -rf results/coverage
    displayName: 'Fix coverage'

  - template: step-publish-results.yml
    parameters:
      artifact: results0
