jobs:
- job: reporting
  dependsOn:
  - tests
  - tests_browser
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - template: step-prepare-environment.yml
  - template: step-composer-install.yml

  - task: DownloadPipelineArtifact@2
    inputs:
      path: $(System.DefaultWorkingDirectory)/results
  - bash: |
      pushd ${SYSTEM_DEFAULTWORKINGDIRECTORY}/results
      for f in $(ls); do cp -rf $f/* .; rm -rf $f; done

  - bash: |
      yarn global add junit-merge
      $(yarn global bin)/junit-merge --recursive --dir results/junit --out results/results.xml
    displayName: 'Merge junit files'

  - template: step-runsonar.yml
