jobs:
- job: tests
  pool:
    vmImage: 'ubuntu-latest'
  strategy:
    parallel: 4
  steps:
  - template: step-prepare-environment.yml
  - template: step-composer-install.yml
  - template: step-remove-xdebug.yml
  - template: step-prepare-db.yml
  - template: step-seed-test-db.yml

  - template: step-test-unit.yml

  - template: step-publish-results.yml
    parameters:
      artifact: results$(System.JobPositionInPhase)
