steps:
- script: scripts/ci/rebase.sh
  displayName: Rebase sources

- bash: |
    sudo update-alternatives --set php /usr/bin/php$(phpVersion)
    sudo update-alternatives --set phar /usr/bin/phar$(phpVersion)
    sudo update-alternatives --set phpdbg /usr/bin/phpdbg$(phpVersion)
    sudo update-alternatives --set php-cgi /usr/bin/php-cgi$(phpVersion)
    sudo update-alternatives --set phar.phar /usr/bin/phar.phar$(phpVersion)
    sudo apt-get install php$(phpVersion)-intl
    php -version
  displayName: Set php version $(phpVersion)

- bash: |
    mkdir -p results/coverage
    sed 's/DB_TEST_PASSWORD=/DB_TEST_PASSWORD=root/' scripts/ci/.env.mysql > .env
    touch .sentry-release
  displayName: Prepare environment
