jobs:
- job: tests_browser
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - template: prepare-environment-step.yml
  - template: composer-install-step.yml
  - template: prepare-db-step.yml
  - template: seed-test-db-step.yml

  - bash: |
      export DISPLAY=:99
      echo "##vso[task.setvariable variable=DISPLAY]$DISPLAY"
      Xvfb :99 -screen 0 1280x1024x24 &
      php artisan dusk:chrome-driver $(google-chrome -version | awk '{ print $3 }' | cut -d . -f 1)
      /usr/bin/google-chrome --headless --disable-gpu --disable-dev-shm-usage --remote-debugging-port=9222 http://localhost &
    displayName: 'Launch google chrome'

  - bash: |
      php -S localhost:8000 -t public scripts/tests/server-cc.php &
      php -S localhost:8001 -t public scripts/tests/server-cc.php &
    displayName: 'Run http server'

  - bash: |
      export CHROME_DRIVER_OPTS="--headless --disable-gpu --disable-dev-shm-usage --no-sandbox --remote-debugging-port=9222"
      php artisan dusk --log-junit results/junit/dusk/results.xml
    displayName: 'Run browser tests'

  - task: PublishTestResults@2
    displayName: 'Publish Test Results'
    inputs:
      testResultsFormat: JUnit
      testResultsFiles: 'results*.xml'
      searchFolder: '$(System.DefaultWorkingDirectory)/results/junit/dusk'
      mergeTestResults: true
    condition: succeededOrFailed()

  - bash: |
      vendor/bin/phpcov merge --clover=results/coverage.xml results/coverage/
      rm -rf results/coverage
    displayName: 'Fix coverage'

  - task: PublishPipelineArtifact@0
    inputs:
      artifactName: 'results'
      targetPath: 'results'
