version: "3.4"

services:
  app:
    build: .
    image: monicahq/monicahq:fpm
    depends_on:
      - mysql
    env_file: .env
    volumes:
      - monica_data:/var/www/monica/storage
      - monica_www:/var/www/monica
    restart: always

  web:
    build: ./web
    restart: always
    ports:
      - 80:80
    volumes:
      - monica_www:/var/www/monica:ro
    depends_on:
      - app

  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=sekret_root_password
      - MYSQL_DATABASE=monica
      - MYSQL_USER=homestead
      - MYSQL_PASSWORD=secret
    volumes:
      - monica_mysql:/var/lib/mysql
    restart: always

volumes:
  monica_data:
    name: monica_data
  monica_www:
    name: monica_www
  monica_mysql:
    name: monica_mysql
